GET http://localhost:3000/shoppinglists

#GET http://localhost:3000/shoppinglists/65c17b768983dc88ac5afd40

# POST http://localhost:3000/shoppinglists

# Content-Type: application/json # { # "title": "testing" # }